Update zap_scan.yaml

diff --git a/.github/workflows/zap_scan.yaml b/.github/workflows/zap_scan.yaml
--- a/.github/workflows/zap_scan.yaml
+++ b/.github/workflows/zap_scan.yaml
@@ -33,8 +33,8 @@ jobs:
           date=$(date +'%Y-%m-%d')
           echo "${{ steps.zap_scan_step.outputs.result }}" >> zap_scans/zap_scan_${date}.txt
       
-      - name: handle errors
-        if: failure()
-        run: |
-          echo "ZAP scan failed!"
-          exit 1
+    #  - name: handle errors
+       # if: failure()
+      #  run: |
+      #    echo "ZAP scan failed!"
+       #   exit 1
